import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import CustomCursor from "../../Components/ui/CustomCursor";
import "@/globals.css";

export const metadata: Metadata = {
  title: "Arby",
  description: "Generated by create next app",
};

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${spaceGrotesk.variable}`}>
      <body className="bg-[hsl(204,8%,12%)] font-sans text-white overflow-x-hidden">
        <div className="relative isolate z-0">
        {children}
        </div>
      <CustomCursor />
      </body>
    </html>
  );
}
